name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  CreateRelease:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: "1"

      - name: Lint Go Files
        uses: golangci/golangci-lint-action@v2

      - name: Go Build
        run: |
          go mod vendor
          go build -mod=vendor -o kubediff

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: kubediff
