name: Test Release

on:
  release:
    types:
      - created
      - published

jobs:
  TestRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0

      - name: kubectl apply
        run: |
          kubectl apply -f test_assets/original.yml

      - name: KubeDiff
        uses: yoo/kubediff-action@main
        with:
          manifests: "test_assets/update.yml"
          comment_pr: false

      - name: Read .version File
        run: |
          KUBEDIFF_VERSION="$(cat .version)"
          echo "KUBEDIFF_VERSION=${KUBEDIFF_VERSION}" >> "${GITHUB_ENV}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/v${{ env.KUBEDIFF_VERSION }}
          base: v1
          title: Release v${{ env.KUBEDIFF_VERSION }}
