name: TestPR

on:
  pull_request:
    branches:
      - main

jobs:
  TestPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - name: Lint Go Files
        uses: golangci/golangci-lint-action@v3

      - name: Go Build
        run: |
          go build -mod=vendor -o kubediff
          sudo mv kubediff /usr/bin

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0

      - name: kubectl apply
        run: |
          kubectl apply -f test_assets/original.yml

      - name: KubeDiff
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifests: "test_assets/update.yml"
          debug: true
